name: Lint, Compile & Test

on: 
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  lintBuildTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install NPM Packages
      run: npm install

    - name: Run Linter
      run: npm run lint

    - name: Compile TypeScript
      run: npm run compile

    - name: Run Unit Tests
      run: npx jest

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: /coverage/clover.xml
        badge: true
        format: markdown

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        path: code-coverage-results.md