#
# Runs when a release is created
# Publishes the extension to the VS Marketplace
# Also packages the vsix file and uploads it to the corresponding release
#

name: Publish & Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install NPM Packages
        run: npm install

      - name: Publish to Visual Studio Marketplace
        id: publish
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com

      - name: Rename Package
        run: |
          mv ${{ steps.publish.outputs.vsixPath }} irarainey.${{ steps.publish.outputs.vsixPath }}

      - name: Upload extension package to release
        id: upload-release-asset 
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: irarainey.${{ steps.publish.outputs.vsixPath }}
